Repository DorCarmi/eCommerce, pull requests merged in 2021-04, with the labels that each got.

#30 Store feature
  Tests/BasketTest.cs
  Tests/ExampleTest.cs
  Tests/ItemTest.cs
  Tests/Mokups/mokCart.cs
  Tests/Mokups/mokStore.cs
  Tests/Mokups/mokUserAlice.cs
  eCommerce/Adapters/IPaymentAdapter.cs
  eCommerce/Adapters/ISupplyAdapter.cs
  eCommerce/Adapters/PaymentProxy.cs
  eCommerce/Adapters/SupplyProxy.cs
  eCommerce/Business/Basics/Answer.cs
  eCommerce/Business/Basket.cs
  eCommerce/Business/BasketInfo.cs
  eCommerce/Business/Cart.cs
  eCommerce/Business/CartInfo.cs
  eCommerce/Business/DefaultDiscountStrategy.cs
  eCommerce/Business/DefaultPurchasePolicy.cs
  eCommerce/Business/DefulatPurchaseStrategy.cs
  eCommerce/Business/DiscountPolicy.cs
  eCommerce/Business/DiscountRule.cs
  eCommerce/Business/DiscountStrategy.cs
  eCommerce/Business/Enums/PurchaseStrategyName.cs
  eCommerce/Business/Enums/StorePermission.cs
  eCommerce/Business/IBasket.cs
  eCommerce/Business/ICart.cs
  eCommerce/Business/IStore.cs
  eCommerce/Business/IUser.cs
  eCommerce/Business/Item.cs
  eCommerce/Business/ItemInfo.cs
  eCommerce/Business/ItemsInventory.cs
  eCommerce/Business/PaymentInfo.cs
  eCommerce/Business/PurchasePolicy.cs
  eCommerce/Business/PurchaseRecord.cs
  eCommerce/Business/PurchaseStrategy.cs
  eCommerce/Business/PurhcasePolicy.cs
  eCommerce/Business/Store.cs
  eCommerce/Business/StoreInfo.cs
  eCommerce/Business/StorePermissions.cs
  eCommerce/Business/StoreTransactionHistory.cs
  eCommerce/Business/Transaction.cs
  eCommerce/Business/User.cs
  eCommerce/Common/Result.cs
  eCommerce/PurchaseInfo.cs
Labels: priority1

#32 Tests
  Tests/AccetanceTests.cs
  eCommerce/Business/MarketFacade.cs
  eCommerce/Business/Service/IMarketFacade.cs
Labels: priority1

#41 E market
  Tests/AccetanceTests.cs
  Tests/Business/UserAuthMock.cs
  Tests/Business/UserManagerTests.cs
  Tests/Mokups/mokCart.cs
  Tests/Mokups/mokStore.cs
  Tests/Mokups/mokUserAlice.cs
  Tests/UserStoreIntegration.cs
  eCommerce/Auth/UserAuth.cs
  eCommerce/Business/Cart.cs
  eCommerce/Business/DefaultDiscountStrategy.cs
  eCommerce/Business/DefulatPurchaseStrategy.cs
  eCommerce/Business/ICart.cs
  eCommerce/Business/IStore.cs
  eCommerce/Business/IUser.cs
  eCommerce/Business/Item.cs
  eCommerce/Business/ItemInfo.cs
  eCommerce/Business/ItemsInventory.cs
  eCommerce/Business/MarketFacade.cs
  eCommerce/Business/Member.cs
  eCommerce/Business/OwnerAppointment.cs
  eCommerce/Business/PurchaseRecord.cs
  eCommerce/Business/PurchaseStrategy.cs
  eCommerce/Business/Service/BasketDto.cs
  eCommerce/Business/Service/CartDto.cs
  eCommerce/Business/Service/DtoUtils.cs
  eCommerce/Business/Service/IItem.cs
  eCommerce/Business/Service/IMarketFacade.cs
  eCommerce/Business/Service/IPurchaseHistory.cs
  eCommerce/Business/Service/ItemDto.cs
  eCommerce/Business/Service/StaffPermission.cs
  eCommerce/Business/Service/StoreDto.cs
  eCommerce/Business/Store.cs
  eCommerce/Business/StoreRepository.cs
  eCommerce/Business/User.cs
  eCommerce/Business/UserManager.cs
  eCommerce/Common/ConcurrentIdGenerator.cs
  eCommerce/Common/RegexUtils.cs
Labels: tests

#57 Asp setup
  .gitignore
  eCommerce/.idea/.idea.eCommerce/.idea/inspectionProfiles/Project_Default.xml
  eCommerce/.idea/.idea.eCommerce/.idea/jsLibraryMappings.xml
  eCommerce/Business/IMarketFacade.cs
  eCommerce/Business/MarketFacade.cs
  eCommerce/Business/UserManager.cs
  eCommerce/ClientApp/.env
  eCommerce/ClientApp/.gitignore
  eCommerce/ClientApp/README.md
  eCommerce/ClientApp/package-lock.json
  eCommerce/ClientApp/package.json
  eCommerce/ClientApp/public/index.html
  eCommerce/ClientApp/public/manifest.json
  eCommerce/ClientApp/src/Api/ApiPaths.js
  eCommerce/ClientApp/src/Api/AuthApi.js
  eCommerce/ClientApp/src/App.js
  eCommerce/ClientApp/src/App.test.js
  eCommerce/ClientApp/src/Common.js
  eCommerce/ClientApp/src/components/Home.js
  eCommerce/ClientApp/src/components/Layout.js
  eCommerce/ClientApp/src/components/Login.css
  eCommerce/ClientApp/src/components/Login.js
  eCommerce/ClientApp/src/components/MessageExample.js
  eCommerce/ClientApp/src/components/NavMenu.css
  eCommerce/ClientApp/src/components/NavMenu.js
  eCommerce/ClientApp/src/components/Register.css
  eCommerce/ClientApp/src/components/Register.js
  eCommerce/ClientApp/src/components/WebSocketExample.js
  eCommerce/ClientApp/src/custom.css
  eCommerce/ClientApp/src/index.js
  eCommerce/ClientApp/src/registerServiceWorker.js
  eCommerce/Communication/AuthMiddleware.cs
  eCommerce/Communication/AuthMiddlewareExtenstion.cs
  eCommerce/Controllers/AuthController.cs
  eCommerce/Pages/Error.cshtml
  eCommerce/Pages/Error.cshtml.cs
  eCommerce/Pages/_ViewImports.cshtml
  eCommerce/Service/AuthService.cs
  eCommerce/Service/IAuthService.cs
  eCommerce/SingleR/MessageHub.cs
  eCommerce/Startup.cs
  eCommerce/eCommerce.csproj
Labels: set-up
